config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root "articles#index"

  resources :articles do
    resources :comments
  end

  resources :users do
    resources :relationships, only: [:create]
  end

  resources :relationships, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
# frozen_string_literal: true

# article model
class Article < ApplicationRecord
  include Visible

  has_many :comments, dependent: :destroy
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/comment.rb
# frozen_string_literal: true

# comment model
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  belongs_to :user
end

app/models/concerns/visible.rb
# frozen_string_literal: true

# module to handle the comment and article statuses
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = %w[public private archived].freeze

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :followers, foreign_key: 'followed_id', class_name: 'Relationship'
  has_many :following, foreign_key: 'follower_id', class_name: 'Relationship'

  has_many :comments, dependent: :destroy
  has_many :articles, dependent: :destroy

  validates :email, presence: true
  validates :password, presence: true, length: { minimum: 6 }

  def username
    email.split('@')[0].capitalize
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
# frozen_string_literal: true

# class to handle article requests
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = current_user.articles.create(article_params)
    if @article.save
      redirect_to @article
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
# class to handle comment requests
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    current_user.comments.append(@comment)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :authenticate_user!

  def create
    blogger = User.find(params[:user_id])
    @rel = Relationship.new(
      follower_id: current_user.id,
      followed_id: blogger.id)
    if @rel.save
      redirect_to user_path(blogger)
    else
      redirect_to root_path
    end
  end

  def destroy
    @rel = Relationship.find(params[:id])
    if @rel.destroy
      redirect_to user_path(@rel.followed_id)
    else
      redirect_to root_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = User.find(params[:id])
    @rel = @user.followers.find_by(follower: current_user)
  end
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div class="form-group">
    <%= form.label :title, :class => 'h6' %><br>
    <%= form.text_field :title, class: 'form-control' %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div style='color: red'><%= message %></div>
    <% end %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :body, :class => 'h6' %>
    <%= form.text_area :body, class: 'form-control' %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div style='color: red'><%= message %></div>
    <% end %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :status, :class => 'h6' %>:
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit :class => 'btn btn-primary' %>
    <%= link_to "Back", root_path, :class => 'btn btn-secondary' %>
  </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1 class="h1-articles" align="center">Edit Article</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="text-center">
  <h1 class="h1-articles">Articles</h1>
  <div>
    <p>Our blog has <%= Article.public_count %> articles and counting...</p>
  </div>
  <div class="row">
    <% @articles.each do |article| %>
      <%unless article.archived? %>
        <div class="col-sm-4">
          <div class="card border-info rounded shadow p-3 mb-5 bg-white" style="width: 18rem;">
            <div class="card-body">
              <small><%= article.created_at.to_date %></small><br>
              <h3 class='article_title'><%= article.title %></h3>
              <p class="card-text text-justify"><%= article.body[0..50] %>...</p>
            </div>
            <small><%= link_to "Continue reading", article %></small>
            <br>
          </div>
          <p></p>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= link_to "New Article", new_article_path, :class => "btn btn-primary" %>
</div>
<br>

app/views/articles/new.html.erb
<h1 class="h1-articles" align="center">New Article</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<br>
<p><%= link_to "Go to   #{@article.user.username} profile", user_path(@article.user.id), :class => 'btn btn-success' %></p>
<p align="left"><%= @article.created_at.to_date %></p>
<p>Author: <%= @article.user.email %></p>
<h1 class='h1-articles'><%= @article.title %></h1>
<br>
<p align="left"><%= @article.body %></p>
<br>
<br>
<div>
  <%= link_to_if @article.user_id.to_i == current_user.id.to_i, "Edit", edit_article_path(@article),
    :class => 'btn btn-warning' %>
  <%= link_to_if @article.user_id.to_i == current_user.id.to_i, "Destroy", article_path(@article),
    method: :delete,
    data: { confirm: "Are you sure?" },
    :class => 'btn btn-danger' %>
  <%= link_to "Back", root_path, :class => 'btn btn-secondary' %>
</div>
<br>
<br>
<br>
<h5>Comments</h5>
<%= render @article.comments %>
<br>
<% if @article.user.followers.find_by(follower: current_user) != nil  %>
  <div class="card border-info rounded shadow p-3 mb-5 bg-white">
    <div class="card-body">
      <h6>Add a comment:</h6>
      <%= render "comments/form" %>
    </div>
  </div>
<% else %>
  <h6>Follow this blog for comment</h6>
  <br>
<% end  %>
<br>

app/views/comments/_comment.html.erb
<br>
<div class="card border-info rounded shadow p-3 mb-5 bg-white">
  <div class="card-body">
    <h6>Commenter: <%= User.find(comment.user_id).email %></h6>
    <%= comment.body %>
    <!--
    <p><%=@article.user_id%></p>
    <p><%=comment.user_id%></p>
    -->
    <p></p>
    <p>
    <%= link_to_if current_user.id.to_i == comment.user_id.to_i, 'Destroy Comment', [comment.article, comment],
              method: :delete,
              data: { confirm: "Are you sure?" },
              :class => 'btn btn-danger btn-sm' %>
    </p>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [ @article, @article.comments.build ] do |form| %>

  <div class="form-group">
    <%= form.label :body, :class => 'h6' %><br>
    <%= form.text_field :body, class: 'form-control' %>
  </div>
  <br>
  <div class="form-group">
    <%= form.label :status, :class => 'h6' %>
    <%= form.select :status, ['public', 'private', 'archived'], selected: 'public', :class => "custom-select custom-select-sm" %>
  </div>
  <br>
  <div class="form-group">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-sm bg-light shadow-sm p-3 mb-5 bg-white rounded">
  <a class="navbar-brand" href="/">Rails Blog</a>
    <ul class="navbar-nav ml-auto">
      <li  class="nav-item">
        <% if user_signed_in? %>
          <%= current_user.email %>
          <%= link_to 'Log_out', destroy_user_session_path, method: :delete, class: 'btn btn-light'  %>
        <% else %>
          <%= link_to 'Log in', new_user_session_path, class: 'btn btn-light' %>
          <%= link_to 'Sign up', new_user_registration_path, class: 'btn btn-light' %>
        <% end %>
      </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kommit Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render 'layouts/header' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="col-sm-10 offset-sm-1">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/users/show.html.erb
<% if current_user.id.to_i !=  @user.id.to_i %>
  <h1> <%= "#{@user.username}'s profile! " %></h1>
  <h6><%= "#{@user.email}" %></h6><br>
  <%= link_to "Follow", user_relationships_path(@user), method: :post, :class => 'btn btn-danger' unless @rel.present? %>
  <%= link_to 'Unfollow', relationship_path(@rel), method: :delete, :class => 'btn btn-danger' if @rel.present? %>
  <br>
  <% else  %>
    <h1>My profile</h1>
    <p><%= "#{@user.email} - #{@user.username}" %></p>
<% end  %>
<br>
<h6>Followers: <%= "#{@user.followers.count} - Following: #{@user.following.count}" %></h6>